POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RuYW1lIiwiaWQiOiI1ZTlkYzBkMWI1N2RjYTI1NjgzMTVhYzEiLCJpYXQiOjE1ODczOTg3Mjh9.wSJAsV86orbI3c6KuHJXwdbAIoC1ZahdaqFNXKVKGnw

{
  "title": "TestiBlog",
  "author": "Herkko",
  "url": "http://test.blog",
  "likes": "51"
}