POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNpaWthbGEiLCJpZCI6IjVlOWRlODBiYWVlOWIwMjQ2YzIwYzJkMCIsImlhdCI6MTU4NzQwNzA5M30.hm6FOaP5nlU0WyORMlrlpYlyMbF6ht0TM8JXuok14GY

{
  "title": "TestBlog",
  "author": "Herkko",
  "url": "http://test.blog",
  "likes": "13"
}